import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import installElementPlus from "./plugins/element";
import "bootstrap/scss/bootstrap.scss";
import Maska from "maska";
const app = createApp(App);
app.use(Maska);
app.use(installElementPlus);
app.use(store).use(router).mount("#app");
